name: CI_main

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set SHORT_SHA
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set BRANCH_NAME
        run: | 
          echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ github.ref == 'refs/heads/main' && secrets.DOCKER_HUB_USERNAME }}/web-fetcher:${{ env.SHORT_SHA }}
            ${{ github.ref == 'refs/heads/main' && secrets.DOCKER_HUB_USERNAME }}/web-fetcher:latest
      -
        name: Upload to code cov
        uses: codecov/codecov-action@v3