name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set CHROMIUM_VERSION from file
        run: |
          export CHROMIUM_VERSION=$(cat chromedriver_version.txt)
        env:
          CHROMIUM_VERSION: ${{ env.CHROMIUM_VERSION }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          build-args: CHROMIUM_VERSION=$CHROMIUM_VERSION
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/web-fetcher:${{ github.sha }}
            ${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_slug }}
