name: CI_pr

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set SHORT_SHA
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Sets MODIFIED_BRANCH_NAME
        env:
          name: ${{env.BRANCH_NAME}}
        run: |
            echo "MODIFIED_BRANCH_NAME=${name/\//-}" >> $GITHUB_ENV
            echo original branch name was $name

      - name: Debug step
        run: |
          cat $GITHUB_ENV
          echo $BRANCH_NAME
          echo $MODIFIED_BRANCH_NAME
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push image
        uses: docker/build-push-action@v2
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ github.ref != 'refs/heads/main' && secrets.DOCKER_HUB_USERNAME }}/web-fetcher:${{ env.MODIFIED_BRANCH_NAME }}
