name: CI_pr

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set CHROMIUM_VERSION from file
        run: |
          echo "CHROMIUM_VERSION=$(cat chromedriver_version.txt)" >> $GITHUB_ENV
      - name: Set SHORT_SHA
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set BRANCH_NAME
        run: | 
          echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
      - name: Any Name Bash Test Step
        run: |
          echo "SHORT_SHA: $SHORT_SHA"
          echo "BRANCH)NAME: $BRANCH_NAME"
          echo "CHROMIUM_VERSION: $CHROMIUM_VERSION"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          build-args: CHROMIUM_VERSION=${{ env.CHROMIUM_VERSION }}
          push: true
          tags: |
            ${{ github.ref != 'refs/heads/main' && secrets.DOCKER_HUB_USERNAME }}/web-fetcher:${{ env.BRANCH_NAME }}
